# Generated by Django 5.0.6 on 2024-07-08 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_alter_customuser_in_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='firstname',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='lastname',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
