# Generated by Django 5.0.6 on 2024-09-20 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_alter_customuser_firstname_alter_customuser_lastname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='in_group',
        ),
    ]
