# Generated by Django 5.0.6 on 2024-07-04 00:50

import datetime
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('givenID', models.CharField(max_length=40)),
                ('group_name', models.CharField(max_length=30)),
                ('group_description', models.CharField(max_length=150)),
                ('created_on', models.DateTimeField(default=datetime.datetime.now, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='home.group')),
            ],
        ),
        migrations.CreateModel(
            name='Table_task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('task_name', models.CharField(max_length=30)),
                ('task_description', models.CharField(max_length=150)),
                ('current_column', models.CharField(max_length=30)),
                ('current_worker', models.CharField(max_length=30)),
                ('deadLine', models.DateTimeField()),
                ('created_on', models.DateTimeField(default=datetime.datetime.now, editable=False)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='home.table')),
            ],
        ),
        migrations.AddField(
            model_name='table',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='home.table_task'),
        ),
        migrations.CreateModel(
            name='Table_taskColumn',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('column_name', models.CharField(max_length=30)),
                ('column_description', models.CharField(max_length=150)),
                ('column_color', models.CharField(max_length=10)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taskColumns', to='home.table')),
            ],
        ),
        migrations.AddField(
            model_name='table',
            name='task_column',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='home.table_taskcolumn'),
        ),
    ]
