# Generated by Django 5.0.6 on 2025-03-15 16:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GroupGivenIDEnding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ending', models.CharField(max_length=10)),
                ('whole_name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('group_name', models.CharField(max_length=30)),
                ('givenID', models.CharField(max_length=40)),
                ('group_password', models.CharField(max_length=30)),
                ('group_biography', models.TextField(blank=True, null=True)),
                ('created_on', models.DateTimeField(default='2025-03-15 17:46:42', editable=False)),
                ('givenID_ending', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Groups', to='home.groupgivenidending')),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('group', models.OneToOneField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.group')),
            ],
        ),
        migrations.CreateModel(
            name='Table_task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('task_name', models.CharField(max_length=30)),
                ('task_description', models.CharField(max_length=150)),
                ('current_column', models.CharField(max_length=30)),
                ('current_worker', models.CharField(max_length=30)),
                ('deadLine', models.DateTimeField()),
                ('created_on', models.DateTimeField(default='2025-03-15 17:46:42', editable=False)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='home.table')),
            ],
        ),
        migrations.CreateModel(
            name='Table_taskColumn',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('column_name', models.CharField(max_length=30)),
                ('column_description', models.CharField(max_length=150)),
                ('column_color', models.CharField(max_length=10)),
                ('position', models.IntegerField()),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taskColumns', to='home.table')),
            ],
        ),
    ]
