# Generated by Django 5.0.6 on 2024-07-04 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='group_password',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
    ]
