# Generated by Django 5.0.6 on 2024-07-04 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_group_group_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='task',
        ),
        migrations.RemoveField(
            model_name='table',
            name='task_column',
        ),
        migrations.AddField(
            model_name='table_taskcolumn',
            name='position',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
