# Generated by Django 5.0.6 on 2025-04-09 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_group_created_on_alter_table_task_created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='created_on',
            field=models.DateTimeField(default='2025-04-09 21:06:59', editable=False),
        ),
        migrations.AlterField(
            model_name='group',
            name='givenID',
            field=models.CharField(max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='table_task',
            name='created_on',
            field=models.DateTimeField(default='2025-04-09 21:06:59', editable=False),
        ),
    ]
