# Generated by Django 5.0.6 on 2025-04-09 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_group_created_on_alter_group_givenid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='created_on',
            field=models.DateTimeField(default='2025-04-09 22:21:56', editable=False),
        ),
        migrations.AlterField(
            model_name='table_task',
            name='created_on',
            field=models.DateTimeField(default='2025-04-09 22:21:56', editable=False),
        ),
    ]
