# Generated by Django 5.0.6 on 2024-07-04 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_table_task_remove_table_task_column_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='created_on',
            field=models.DateTimeField(default='04.07.2024 - 17:42:07', editable=False),
        ),
        migrations.AlterField(
            model_name='table_task',
            name='created_on',
            field=models.DateTimeField(default='04.07.2024 - 17:42:07', editable=False),
        ),
    ]
