# Generated by Django 5.0.6 on 2025-04-12 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_group_created_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='created_on',
            field=models.DateTimeField(default='2025-04-12 15:02:20', editable=False),
        ),
        migrations.AlterField(
            model_name='table_task',
            name='created_on',
            field=models.DateTimeField(default='2025-04-12 15:02:20', editable=False),
        ),
        migrations.AlterField(
            model_name='table_task',
            name='task_description',
            field=models.TextField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='table_taskcolumn',
            name='column_color',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='table_taskcolumn',
            name='column_description',
            field=models.TextField(blank=True, max_length=150, null=True),
        ),
    ]
