# Generated by Django 5.0.6 on 2025-04-16 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_group_created_on_alter_table_task_created_on_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='givenID_ending',
        ),
        migrations.AlterField(
            model_name='group',
            name='created_on',
            field=models.DateTimeField(default='2025-04-17 01:55:47', editable=False),
        ),
        migrations.AlterField(
            model_name='table_task',
            name='created_on',
            field=models.DateTimeField(default='2025-04-17 01:55:47', editable=False),
        ),
    ]
