# Generated by Django 5.2.4 on 2025-07-06 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_remove_group_givenid_ending_alter_group_created_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='created_on',
            field=models.DateTimeField(default='2025-07-06 22:05:02', editable=False),
        ),
        migrations.AlterField(
            model_name='table_task',
            name='created_on',
            field=models.DateTimeField(default='2025-07-06 22:05:02', editable=False),
        ),
    ]
