# Generated by Django 5.0.6 on 2024-07-04 23:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_group_created_on_alter_table_task_created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='created_on',
            field=models.DateTimeField(default='2024-07-05 01:49:59', editable=False),
        ),
        migrations.AlterField(
            model_name='table',
            name='group',
            field=models.OneToOneField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.group'),
        ),
        migrations.AlterField(
            model_name='table_task',
            name='created_on',
            field=models.DateTimeField(default='2024-07-05 01:49:59', editable=False),
        ),
    ]
