# Generated by Django 5.0.6 on 2024-07-06 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_group_created_on_alter_table_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='created_on',
            field=models.DateTimeField(default='2024-07-06 02:16:48', editable=False),
        ),
        migrations.AlterField(
            model_name='table_task',
            name='created_on',
            field=models.DateTimeField(default='2024-07-06 02:16:48', editable=False),
        ),
    ]
