# Generated by Django 5.2.4 on 2025-07-24 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_group_created_on_alter_table_task_created_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='created_on',
            field=models.DateTimeField(default='2025-07-24 19:57:15', editable=False),
        ),
        migrations.AlterField(
            model_name='table_task',
            name='created_on',
            field=models.DateTimeField(default='2025-07-24 19:57:15', editable=False),
        ),
    ]
