# Generated by Django 5.2.4 on 2025-07-29 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_group_created_on_alter_table_task_created_on'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GroupGivenIDEnding',
        ),
        migrations.AlterField(
            model_name='group',
            name='created_on',
            field=models.DateTimeField(default='2025-07-29 02:00:43', editable=False),
        ),
        migrations.AlterField(
            model_name='table_task',
            name='created_on',
            field=models.DateTimeField(default='2025-07-29 02:00:43', editable=False),
        ),
    ]
