# Generated by Django 5.2.4 on 2025-07-29 00:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_delete_groupgivenidending_alter_group_created_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='created_on',
            field=models.DateTimeField(default='2025-07-29 02:11:15', editable=False),
        ),
        migrations.AlterField(
            model_name='table_task',
            name='created_on',
            field=models.DateTimeField(default='2025-07-29 02:11:15', editable=False),
        ),
        migrations.AlterField(
            model_name='table_task',
            name='current_column',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='home.table_taskcolumn'),
        ),
    ]
