# Generated by Django 5.2.4 on 2025-08-06 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_group_created_on_alter_table_task_created_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table_task',
            name='current_column',
            field=models.CharField(choices=[('ToDo', 'ToDo'), ('In progress', 'In progress'), ('Done', 'Done')], max_length=15),
        ),
        migrations.AlterField(
            model_name='group',
            name='created_on',
            field=models.DateTimeField(default='2025-08-06 20:48:22', editable=False),
        ),
        migrations.AlterField(
            model_name='table_task',
            name='created_on',
            field=models.DateTimeField(default='2025-08-06 20:48:22', editable=False),
        ),
        migrations.DeleteModel(
            name='Table_taskColumn',
        ),
    ]
