# Generated by Django 5.2.4 on 2025-08-14 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_alter_table_task_current_column_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='created_on',
            field=models.DateTimeField(default='2025-08-15 01:48:36', editable=False),
        ),
        migrations.AlterField(
            model_name='table_task',
            name='created_on',
            field=models.DateTimeField(default='2025-08-15 01:48:36', editable=False),
        ),
        migrations.AlterField(
            model_name='table_task',
            name='task_name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
