# Generated by Django 5.2.4 on 2025-08-16 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_alter_group_created_on_alter_table_task_created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='created_on',
            field=models.DateTimeField(default='2025-08-16 20:12:27', editable=False),
        ),
        migrations.AlterField(
            model_name='table_task',
            name='created_on',
            field=models.DateTimeField(default='2025-08-16 20:12:27', editable=False),
        ),
        migrations.AlterField(
            model_name='table_task',
            name='table',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='home.table'),
        ),
    ]
