# Generated by Django 5.0.6 on 2024-10-03 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_alter_group_created_on_remove_group_workers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='workers',
        ),
        migrations.AlterField(
            model_name='group',
            name='created_on',
            field=models.DateTimeField(default='2024-10-03 22:49:35', editable=False),
        ),
        migrations.AlterField(
            model_name='table_task',
            name='created_on',
            field=models.DateTimeField(default='2024-10-03 22:49:35', editable=False),
        ),
    ]
