# Generated by Django 5.0.6 on 2024-10-03 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_alter_group_created_on_alter_table_task_created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='created_on',
            field=models.DateTimeField(default='2024-10-03 23:18:12', editable=False),
        ),
        migrations.AlterField(
            model_name='table_task',
            name='created_on',
            field=models.DateTimeField(default='2024-10-03 23:18:12', editable=False),
        ),
    ]
