# Generated by Django 5.0.6 on 2024-11-16 17:32

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0033_alter_group_created_on_alter_table_task_created_on'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupGivenIDEndings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ending', models.CharField(max_length=10)),
                ('whole_name', models.CharField(max_length=40)),
            ],
        ),
        migrations.AlterField(
            model_name='group',
            name='created_on',
            field=models.DateTimeField(default='2024-11-16 18:32:02', editable=False),
        ),
        migrations.AlterField(
            model_name='table_task',
            name='created_on',
            field=models.DateTimeField(default='2024-11-16 18:32:02', editable=False),
        ),
    ]
