# Generated by Django 5.0.6 on 2024-11-16 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0035_rename_groupgivenidendings_groupgivenidending_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='givenID_ending',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Groups', to='home.groupgivenidending'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='group',
            name='created_on',
            field=models.DateTimeField(default='2024-11-16 18:35:56', editable=False),
        ),
        migrations.AlterField(
            model_name='table_task',
            name='created_on',
            field=models.DateTimeField(default='2024-11-16 18:35:56', editable=False),
        ),
    ]
