# Generated by Django 5.0.6 on 2024-11-16 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0038_alter_group_created_on_alter_table_task_created_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='group_description',
        ),
        migrations.AddField(
            model_name='group',
            name='group_biography',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='created_on',
            field=models.DateTimeField(default='2024-11-16 19:13:12', editable=False),
        ),
        migrations.AlterField(
            model_name='table_task',
            name='created_on',
            field=models.DateTimeField(default='2024-11-16 19:13:12', editable=False),
        ),
    ]
